# Generated by Django 4.2.7 on 2023-11-07 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro_hora_extra', '0002_alter_registrohoraextra_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrohoraextra',
            options={'verbose_name': 'Horas Extra'},
        ),
    ]
