# Generated by Django 4.2.7 on 2023-11-07 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro_hora_extra', '0003_alter_registrohoraextra_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrohoraextra',
            options={'verbose_name': 'Horas Extras', 'verbose_name_plural': 'Horas Extras'},
        ),
    ]
