# Generated by Django 4.2.7 on 2023-11-12 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_hora_extra', '0006_registrohoraextra_horas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrohoraextra',
            options={},
        ),
        migrations.AddField(
            model_name='registrohoraextra',
            name='utilizada',
            field=models.BooleanField(default=False),
        ),
    ]
